# Generated by Django 5.2.3 on 2025-06-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessstudio', '0002_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='client_email',
            field=models.EmailField(max_length=250),
        ),
    ]
