# Generated by Django 5.2.3 on 2025-06-21 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessstudio', '0003_alter_bookings_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
